CREATE TABLE IF NOT EXISTS manager_payment_methods (id BIGSERIAL PRIMARY KEY, manager_id VARCHAR(50) NOT NULL REFERENCES managers(id) ON DELETE CASCADE, method_code VARCHAR(50) NOT NULL, display_name VARCHAR(120) NOT NULL, instructions TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(manager_id, method_code));
CREATE TABLE IF NOT EXISTS manual_payment_requests (id BIGSERIAL PRIMARY KEY, manager_id VARCHAR(50) NOT NULL REFERENCES managers(id) ON DELETE CASCADE, customer_id INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE, reservation_id INT REFERENCES reservations(id) ON DELETE SET NULL, invoice_id UUID REFERENCES invoices(id) ON DELETE SET NULL, purpose VARCHAR(40) NOT NULL CHECK (purpose IN ('WALLET_TOPUP','RESERVATION_PAYMENT','MANUAL_GN','MANUAL_LP')), amount NUMERIC(30,10), currency VARCHAR(10) NOT NULL DEFAULT 'IRT', payment_method_id BIGINT REFERENCES manager_payment_methods(id) ON DELETE SET NULL, payment_method_code VARCHAR(50), payment_reference VARCHAR(255), receipt_reference VARCHAR(255), customer_note TEXT, manager_note TEXT, status VARCHAR(40) NOT NULL DEFAULT 'PENDING_MANAGER_REVIEW', rejection_reason TEXT, reviewed_by VARCHAR(50) REFERENCES managers(id) ON DELETE SET NULL, reviewed_at TIMESTAMPTZ, idempotency_key VARCHAR(128) NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE UNIQUE INDEX IF NOT EXISTS uq_manual_payment_request_idempotency ON manual_payment_requests(manager_id, customer_id, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_manual_payment_requests_manager_status ON manual_payment_requests(manager_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_manual_payment_requests_customer ON manual_payment_requests(manager_id, customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_manual_payment_requests_reservation ON manual_payment_requests(manager_id, reservation_id);
CREATE INDEX IF NOT EXISTS idx_manager_payment_methods_active ON manager_payment_methods(manager_id, active);
INSERT INTO manager_payment_methods(manager_id,method_code,display_name,instructions) SELECT m.id,v.method_code,v.display_name,v.instructions FROM managers m CROSS JOIN (VALUES ('CARD_TO_CARD','کارت به کارت','اطلاعات کارت مقصد را از مدیریت دریافت کنید و رسید را ارسال کنید.'),('CRYPTO','رمزارز','آدرس و شبکه پرداخت را از مدیریت دریافت کنید و هش تراکنش را ارسال کنید.'),('OTHER_MANUAL','سایر روش دستی','روش پرداخت و جزئیات را طبق اعلام مدیریت انجام دهید.')) v(method_code,display_name,instructions) ON CONFLICT(manager_id,method_code) DO NOTHING;
CREATE INDEX IF NOT EXISTS idx_manual_payment_requests_status ON manual_payment_requests(status, created_at DESC);
