const {Pool}=require('pg'); const {cancelReservation}=require('./financialService'); require('dotenv').config();
const pool=new Pool({connectionString:process.env.DATABASE_URL}); const mid='cancel_boundary_'+Date.now(); let cid,st;
const policy={atOrAbove24h:{thresholdMinutes:1440,gn:50,lp:50,walletPercent:100},above15h:{thresholdMinutes:900,gn:70,lp:70,walletPercent:90},above5h:{thresholdMinutes:300,gn:120,lp:120,walletPercent:85},above2h:{thresholdMinutes:120,gn:200,lp:200,walletPercent:80},within2h:{thresholdMinutes:0,gn:250,lp:250,walletPercent:70},lateCancellation:{gn:250,lp:250,walletPercent:0}};
async function main(){let pass=0,fail=0; const ok=(x,n)=>{if(x){console.log('PASS:',n);pass++}else{console.log('FAIL:',n);fail++}};
try{await pool.query("INSERT INTO managers(id,username,password_hash,role) VALUES($1,$1,'x','MANAGER')",[mid]); cid=(await pool.query("INSERT INTO customers(manager_id,phone_number,wallet_balance,gn_balance,lp_balance) VALUES($1,$2,0,10,10) RETURNING id",[mid,'cb'+Date.now()])).rows[0].id; st=(await pool.query("INSERT INTO stations(manager_id,name,controller_capacity,reservable,active) VALUES($1,'CB',4,TRUE,TRUE) RETURNING id",[mid])).rows[0].id;
const cases=[['24h',1440*60000+2000,100,50],['just-under-24h',1439*60000+58000,90,70],['15h',900*60000+2000,90,70],['just-under-15h',899*60000+58000,85,120],['5h',300*60000+2000,85,120],['just-under-5h',299*60000+58000,80,200],['2h',120*60000+2000,80,200],['just-under-2h',119*60000+58000,70,250]];
for(const [name,ms,wallet,gn] of cases){const start=new Date(Date.now()+ms), rid=(await pool.query("INSERT INTO reservations(manager_id,customer_id,station_id,type,status,start_time,end_time,duration_minutes,snap_base_price,snap_final_price,snap_payable_amount,snap_deposit_amount,snap_cancellation_policy,snap_vip_policy) VALUES($1,$2,$3,'NORMAL_RESERVATION','CONFIRMED',$4,$5,60,100,100,100,30,$6::jsonb,'{}'::jsonb) RETURNING id",[mid,cid,st,start,new Date(start.getTime()+3600000),JSON.stringify(policy)])).rows[0].id; await pool.query("INSERT INTO payment_transactions(manager_id,customer_id,reservation_id,provider,gateway_transaction_id,amount,currency,status,idempotency_key,verified_at) VALUES($1,$2,$3,'TEST',$4,100,'IRT','SUCCESS',$5,NOW())",[mid,cid,rid,'tx'+rid,'pay'+rid]); const out=await cancelReservation(pool,mid,rid,'boundary'+rid); ok(Number(out.walletPercent)===wallet && Number(out.gnLoss)===gn, name+' boundary policy');}
const bal=await pool.query('SELECT wallet_balance,gn_balance,lp_balance FROM customers WHERE id=$1',[cid]); ok(Number(bal.rows[0].wallet_balance)>=0 && Number(bal.rows[0].gn_balance)>=0 && Number(bal.rows[0].lp_balance)>=0,'wallet/GN/LP never negative');
}catch(e){console.error('BOUNDARY_TEST_ERROR',e.stack||e);fail++} finally{try{await pool.query('DELETE FROM financial_audit_logs WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM payment_transactions WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM wallet_transactions WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM gn_ledger WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM lp_ledger WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM reservations WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM stations WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM customers WHERE manager_id=$1',[mid]);await pool.query('DELETE FROM managers WHERE id=$1',[mid])}catch{}await pool.end();console.log(`Tests Result: Passed: ${pass}, Failed: ${fail}`);if(fail)process.exitCode=1}}
main();
