package com.example.ui

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "GameNexa",
            "main" to "MAIN",
            "settings" to "SETTINGS",
            "statistics" to "STATISTICS",
            "welcome" to "Welcome to the\nGameNexa\nCommunity",
            "prerequisites_desc" to "Please grant the necessary permissions for the app to run in the best state.",
            "battery_optimization_title" to "1. Ignore Battery Optimization",
            "battery_optimization_desc" to "Ensures the app is excluded from system battery savers so it won't be closed. Tap here to open battery settings and select 'Unrestricted' or 'No restrictions'.",
            "enable_notifications_title" to "4. Enable Notifications",
            "enable_notifications_desc" to "Allows the app to vibrate and play sound alerts exactly 1 minute before each session completes. Tap here to open notifications settings.",
            "disable_pause_title" to "3. Prevent App Hibernation",
            "disable_pause_desc" to "Disables 'Pause app activity if unused' so Android won't suspend the app or reset local database data. Tap here to open App Info.",
            "autostart_title" to "2. Enable Background Auto-Start",
            "autostart_desc" to "Allows the app to automatically start/resume on system reboot. Tap here to open autostart or startup settings.",
            "grant_notif_permission" to "Grant Notification Permission",
            "accept_guide" to "Enter Application",
            "number_of_stations" to "Number of Stations",
            "console_types_prices" to "Console Types & Prices",
            "buffet_products" to "Buffet Products",
            "reset_database" to "Reset Database & History",
            "language" to "Language",
            "select_language" to "Select Language",
            "prepay_amount" to "Prepay Amount",
            "cost" to "Play Cost",
            "buffet_cost" to "Buffet Cost",
            "total_cost" to "Total Cost",
            "start" to "Start",
            "pause" to "Pause",
            "resume" to "Resume",
            "stop" to "Stop",
            "finish" to "Finish",
            "available" to "Available",
            "active" to "Active",
            "paused" to "Paused",
            "status" to "Status",
            "controllers" to "Controllers",
            "add_console" to "Add Console Type",
            "console_name_placeholder" to "Console Name (e.g. Steam Deck)",
            "save_prices" to "Save Prices",
            "delete" to "Delete",
            "add_product" to "Add Product",
            "product_name" to "Product Name",
            "product_price" to "Price",
            "save" to "Save",
            "update_product" to "Update Product",
            "reset_all_data" to "RESET ALL DATA",
            "today_income" to "TODAY'S INCOME",
            "monthly_income" to "THIS MONTH'S INCOME",
            "total_income" to "TOTAL HISTORIC INCOME",
            "daily_income_chart" to "Daily Income (Last 30 Days)",
            "monthly_breakdown" to "Monthly Breakdown",
            "no_history" to "No history recorded yet.",
            "notifications_enabled" to "Enable Notification Warnings (1 min remaining)",
            "add_buffet_item" to "Add Buffet Product to Station",
            "ordered_buffet_items" to "Ordered Buffet Items (Total Buffet Cost: %s)",
            "add_item" to "Add Item",
            "delete_confirm" to "Are you sure you want to delete?",
            "station_count_label" to "Set station count",
            "station_number_prefix" to "Station",
            "warning_dismiss" to "Dismiss",
            "warning_remaining" to "Station %d: %d minutes remaining",
            "station" to "Station",
            "controller_suffix" to "CTL",
            "customers_and_reservations" to "CUSTOMERS & RESERVATIONS",
            "customers_tab" to "CUSTOMERS",
            "reservations_tab" to "RESERVATIONS",
            "add_customer" to "Register Customer",
            "full_name" to "Full Name",
            "phone_number" to "Phone Number",
            "debt" to "Debt (Toman)",
            "credit" to "Credit (Toman)",
            "description" to "Description",
            "cancel" to "Cancel",
            "customer_saved" to "Customer saved successfully",
            "reservation_saved" to "Reservation saved successfully",
            "add_reservation" to "Register Reservation",
            "reservation_time" to "Reservation Time & Date",
            "reservation_duration" to "Duration (minutes)",
            "no_customers" to "No registered customers yet.",
            "no_reservations" to "No upcoming reservations registered.",
            "contact_permission_needed" to "Contacts permission is required to select from contacts.",
            "select_contact" to "Pick from Contacts",
            "enter_duration_error" to "Please enter a valid duration",
            "contact_us" to "CONTACT US",
            "email_gateway" to "Email Gateway",
            "developer" to "Developer",
            "contact_desc" to "Please share your feedback and suggestions with us through the in-app email or comments on Cafebazaar, Myket, etc.",
            "thanks_for_choosing" to "Thank you for choosing us"
        ),
        "fa" to mapOf(
            "app_name" to "GameNexa",
            "main" to "اصلی",
            "settings" to "تنظیمات",
            "statistics" to "آمار",
            "welcome" to "به جامعه بزرگ\nGameNexa\nخوشامدید",
            "prerequisites_desc" to "لطفا برای اجرای برنامه در بهترین حالت،دسترسی به مجوز ها را صادر کنید.",
            "battery_optimization_title" to "1. نادیده گرفتن بهینه‌سازی باتری",
            "battery_optimization_desc" to "جلوگیری از بسته شدن خودکار برنامه توسط ذخیره‌سازهای باتری سیستم. برای باز کردن تنظیمات باتری و انتخاب گزینه «بدون محدودیت» (Unrestricted یا No restrictions) اینجا را لمس کنید.",
            "enable_notifications_title" to "4. فعال‌سازی نوتیفیکیشن‌ها",
            "enable_notifications_desc" to "به برنامه اجازه می‌دهد دقیقاً 1 دقیقه قبل از اتمام بازی، لرزش و هشدار صوتی پخش کند. برای باز کردن تنظیمات اعلان‌ها اینجا را لمس کنید.",
            "disable_pause_title" to "3. غیرفعال‌سازی «توقف فعالیت برنامه در صورت عدم استفاده»",
            "disable_pause_desc" to "جلوگیری از اینکه سیستم‌عامل اندروید در صورت عدم استفاده چند روزه، دیتابیس محلی برنامه را به خواب ببرد یا اطلاعات آن را ریست کند. برای باز کردن اطلاعات برنامه اینجا را لمس کنید.",
            "autostart_title" to "2. فعال‌سازی شروع خودکار در پس‌زمینه",
            "autostart_desc" to "به برنامه اجازه می‌دهد در زمان روشن شدن یا راه‌اندازی مجدد گوشی به درستی کار خود را به صورت خودکار ادامه دهد. برای باز کردن تنظیمات مدیریت شروع خودکار اینجا را لمس کنید.",
            "grant_notif_permission" to "اعطای مجوز نوتیفیکیشن",
            "accept_guide" to "ورود به برنامه",
            "number_of_stations" to "تعداد ایستگاه‌ها (تلویزیون‌ها)",
            "console_types_prices" to "انواع کنسول و قیمت‌ها",
            "buffet_products" to "محصولات کافه",
            "reset_database" to "پاکسازی پایگاه داده و تاریخچه",
            "language" to "زبان / Language",
            "select_language" to "انتخاب زبان",
            "prepay_amount" to "مبلغ پیش‌پرداخت",
            "cost" to "هزینه بازی",
            "buffet_cost" to "هزینه کافه",
            "total_cost" to "هزینه کل",
            "start" to "شروع",
            "pause" to "توقف موقت",
            "resume" to "ادامه",
            "stop" to "توقف",
            "finish" to "تسویه",
            "available" to "آماده به کار",
            "active" to "فعال",
            "paused" to "متوقف شده",
            "status" to "وضعیت",
            "controllers" to "دسته بازی",
            "add_console" to "افزودن نوع کنسول",
            "console_name_placeholder" to "نام کنسول (مثلا PS5 یا Xbox)",
            "save_prices" to "ذخیره قیمت‌ها",
            "delete" to "حذف",
            "add_product" to "افزودن محصول کافه",
            "product_name" to "نام محصول",
            "product_price" to "قیمت",
            "save" to "ذخیره",
            "update_product" to "بروزرسانی محصول",
            "reset_all_data" to "پاکسازی کامل تمامی داده‌ها",
            "today_income" to "درآمد امروز",
            "monthly_income" to "درآمد این ماه",
            "total_income" to "کل درآمد تاریخی",
            "daily_income_chart" to "درآمد روزانه (30 روز گذشته)",
            "monthly_breakdown" to "تفکیک ماهانه",
            "no_history" to "هنوز هیچ تاریخچه‌ای ثبت نشده است.",
            "notifications_enabled" to "فعال‌سازی هشدارهای نوتیفیکیشن (1 دقیقه مانده به اتمام)",
            "add_buffet_item" to "افزودن محصول کافه به ایستگاه",
            "ordered_buffet_items" to "خوراکی‌های سفارش داده شده (کل هزینه کافه: %s)",
            "add_item" to "افزودن خوراکی",
            "delete_confirm" to "آیا از حذف اطمینان دارید؟",
            "station_count_label" to "تنظیم تعداد تلویزیون/ایستگاه",
            "station_number_prefix" to "ایستگاه",
            "warning_dismiss" to "بستن",
            "warning_remaining" to "ایستگاه %d: %d دقیقه باقی مانده است",
            "station" to "ایستگاه",
            "controller_suffix" to "دسته",
            "customers_and_reservations" to "مشتری و رزرو",
            "customers_tab" to "مشتریان",
            "reservations_tab" to "رزروها",
            "add_customer" to "ثبت مشتری جدید",
            "full_name" to "نام و نام خانوادگی",
            "phone_number" to "شماره تماس",
            "debt" to "تومان بدهکار",
            "credit" to "تومان طلب کار",
            "description" to "توضیحات",
            "cancel" to "لغو و انصراف",
            "customer_saved" to "مشتری با موفقیت ثبت شد",
            "reservation_saved" to "رزرو با موفقیت ثبت شد",
            "add_reservation" to "ثبت رزرو جدید",
            "reservation_time" to "تاریخ و ساعت رزرو",
            "reservation_duration" to "مدت زمان رزرو (دقیقه)",
            "no_customers" to "هنوز هیچ مشتری ثبت نشده است.",
            "no_reservations" to "هنوز هیچ رزروی ثبت نشده است.",
            "contact_permission_needed" to "برای انتخاب از مخاطبین به مجوز دسترسی به مخاطبین نیاز است.",
            "select_contact" to "انتخاب از مخاطبین",
            "enter_duration_error" to "لطفاً مدت زمان معتبری وارد کنید",
            "contact_us" to "ارتباط با ما",
            "email_gateway" to "درگاه ایمیل",
            "developer" to "توسعه دهنده",
            "contact_desc" to "لطفا انتقاد و پیشنهادات خود را از طریق ایمیل درون برنامه یا کامنت های درون برنامه های بازار یا مایکت یا... با ما در میان بگذارید",
            "thanks_for_choosing" to "با تشکر از انتخاب شما"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
